"""Reviewed BBBike source names and geographic metadata, 2026-09-12.

Names come from https://data.bbbike.org/osm/region/ page titles; country codes
represent reviewed geographic identities. This is not a membership allowlist.
Unknown future packages remain discoverable with unknown geography.
"""
import re
from html import unescape

COUNTRY_CODES = {'algeria': ('DZ',), 'angola': ('AO',), 'benin': ('BJ',), 'botswana': ('BW',), 'burkina-faso': ('BF',), 'burundi': ('BI',), 'cameroon': ('CM',), 'canary-islands': ('ES',), 'cape-verde': ('CV',), 'central-african-republic': ('CF',), 'chad': ('TD',), 'comores': ('KM',), 'congo-brazzaville': ('CG',), 'congo-democratic-republic': ('CD',), 'djibouti': ('DJ',), 'egypt': ('EG',), 'equatorial-guinea': ('GQ',), 'eritrea': ('ER',), 'ethiopia': ('ET',), 'gabon': ('GA',), 'ghana': ('GH',), 'guinea': ('GN',), 'guinea-bissau': ('GW',), 'ivory-coast': ('CI',), 'kenya': ('KE',), 'lesotho': ('LS',), 'liberia': ('LR',), 'libya': ('LY',), 'madagascar': ('MG',), 'malawi': ('MW',), 'mali': ('ML',), 'mauritania': ('MR',), 'mauritius': ('MU',), 'morocco': ('MA',), 'mozambique': ('MZ',), 'namibia': ('NA',), 'niger': ('NE',), 'nigeria': ('NG',), 'rwanda': ('RW',), 'saint-helena-ascension-and-tristan-da-cunha': ('SH',), 'sao-tome-and-principe': ('ST',), 'senegal-and-gambia': ('SN', 'GM'), 'seychelles': ('SC',), 'sierra-leone': ('SL',), 'somalia': ('SO',), 'south-africa': ('ZA',), 'south-africa-and-lesotho': ('ZA', 'LS'), 'south-sudan': ('SS',), 'sudan': ('SD',), 'swaziland': ('SZ',), 'tanzania': ('TZ',), 'togo': ('TG',), 'tunisia': ('TN',), 'uganda': ('UG',), 'zambia': ('ZM',), 'zimbabwe': ('ZW',), 'afghanistan': ('AF',), 'armenia': ('AM',), 'azerbaijan': ('AZ',), 'bangladesh': ('BD',), 'bhutan': ('BT',), 'cambodia': ('KH',), 'china': ('CN',), 'east-timor': ('TL',), 'gcc-states': ('AE', 'BH', 'KW', 'OM', 'QA', 'SA'), 'india': ('IN',), 'indonesia': ('ID', 'TL'), 'iran': ('IR',), 'iraq': ('IQ',), 'israel-and-palestine': ('IL', 'PS'), 'japan': ('JP',), 'jordan': ('JO',), 'kazakhstan': ('KZ',), 'kyrgyzstan': ('KG',), 'laos': ('LA',), 'lebanon': ('LB',), 'malaysia-singapore-brunei': ('MY', 'SG', 'BN'), 'maldives': ('MV',), 'mongolia': ('MN',), 'myanmar': ('MM',), 'nepal': ('NP',), 'north-korea': ('KP',), 'pakistan': ('PK',), 'philippines': ('PH',), 'south-korea': ('KR',), 'sri-lanka': ('LK',), 'syria': ('SY',), 'taiwan': ('TW',), 'tajikistan': ('TJ',), 'thailand': ('TH',), 'turkmenistan': ('TM',), 'uzbekistan': ('UZ',), 'vietnam': ('VN',), 'yemen': ('YE',), 'australia': ('AU',), 'fiji': ('FJ',), 'kiribati': ('KI',), 'marshall-islands': ('MH',), 'micronesia': ('FM',), 'new-caledonia': ('NC',), 'new-zealand': ('NZ',), 'papua-new-guinea': ('PG',), 'polynesie-francaise': ('PF',), 'samoa': ('WS',), 'solomon-islands': ('SB',), 'tonga': ('TO',), 'vanuatu': ('VU',), 'bahamas': ('BS',), 'belize': ('BZ',), 'costa-rica': ('CR',), 'cuba': ('CU',), 'el-salvador': ('SV',), 'guatemala': ('GT',), 'haiti-and-domrep': ('HT', 'DO'), 'honduras': ('HN',), 'jamaica': ('JM',), 'nicaragua': ('NI',), 'panama': ('PA',), 'albania': ('AL',), 'alps': ('AT', 'CH', 'DE', 'FR', 'IT', 'LI', 'SI'), 'andorra': ('AD',), 'austria': ('AT',), 'azores': ('PT',), 'belarus': ('BY',), 'belgium': ('BE',), 'bosnia-herzegovina': ('BA',), 'britain-and-ireland': ('GB', 'IE'), 'bulgaria': ('BG',), 'croatia': ('HR',), 'cyprus': ('CY',), 'czech-republic': ('CZ',), 'dach': ('DE', 'AT', 'CH'), 'denmark': ('DK',), 'estonia': ('EE',), 'faroe-islands': ('FO',), 'finland': ('FI',), 'france': ('FR',), 'georgia': ('GE',), 'germany': ('DE',), 'greece': ('GR',), 'guernsey-jersey': ('GG', 'JE'), 'hungary': ('HU',), 'iceland': ('IS',), 'ireland-and-northern-ireland': ('IE', 'GB'), 'isle-of-man': ('IM',), 'italy': ('IT',), 'kosovo': ('XK',), 'latvia': ('LV',), 'liechtenstein': ('LI',), 'lithuania': ('LT',), 'luxembourg': ('LU',), 'macedonia': ('MK',), 'malta': ('MT',), 'moldova': ('MD',), 'monaco': ('MC',), 'montenegro': ('ME',), 'netherlands': ('NL',), 'norway': ('NO',), 'poland': ('PL',), 'portugal': ('PT',), 'romania': ('RO',), 'serbia': ('RS',), 'slovakia': ('SK',), 'slovenia': ('SI',), 'spain': ('ES',), 'sweden': ('SE',), 'switzerland': ('CH',), 'turkey': ('TR',), 'ukraine': ('UA',), 'united-kingdom': ('GB',), 'canada': ('CA',), 'greenland': ('GL',), 'mexico': ('MX',), 'us-midwest': ('US',), 'us-northeast': ('US',), 'us-south': ('US',), 'us-west': ('US',), 'argentina': ('AR',), 'bolivia': ('BO',), 'brazil': ('BR',), 'chile': ('CL',), 'colombia': ('CO',), 'ecuador': ('EC',), 'guyana': ('GY',), 'paraguay': ('PY',), 'peru': ('PE',), 'suriname': ('SR',), 'uruguay': ('UY',), 'venezuela': ('VE',)}

REGION_NAMES = {
    "africa/algeria": "Algeria",
    "africa/angola": "Angola",
    "africa/benin": "Benin",
    "africa/botswana": "Botswana",
    "africa/burkina-faso": "Burkina Faso",
    "africa/burundi": "Burundi",
    "africa/cameroon": "Cameroon",
    "africa/canary-islands": "Canary Islands",
    "africa/cape-verde": "Cape Verde",
    "africa/central-african-republic": "Central African Republic",
    "africa/chad": "Chad",
    "africa/comores": "Comoros",
    "africa/congo-brazzaville": "Congo (Republic/Brazzaville)",
    "africa/congo-democratic-republic": "Congo (Democratic Republic/Kinshasa)",
    "africa/djibouti": "Djibouti",
    "africa/egypt": "Egypt",
    "africa/equatorial-guinea": "Equatorial Guinea",
    "africa/eritrea": "Eritrea",
    "africa/ethiopia": "Ethiopia",
    "africa/gabon": "Gabon",
    "africa/ghana": "Ghana",
    "africa/guinea": "Guinea",
    "africa/guinea-bissau": "Guinea-Bissau",
    "africa/ivory-coast": "Côte d’Ivoire",
    "africa/kenya": "Kenya",
    "africa/lesotho": "Lesotho",
    "africa/liberia": "Liberia",
    "africa/libya": "Libya",
    "africa/madagascar": "Madagascar",
    "africa/malawi": "Malawi",
    "africa/mali": "Mali",
    "africa/mauritania": "Mauritania",
    "africa/mauritius": "Mauritius",
    "africa/morocco": "Morocco",
    "africa/mozambique": "Mozambique",
    "africa/namibia": "Namibia",
    "africa/niger": "Niger",
    "africa/nigeria": "Nigeria",
    "africa/rwanda": "Rwanda",
    "africa/saint-helena-ascension-and-tristan-da-cunha": "Saint Helena, Ascension, and Tristan da Cunha",
    "africa/sao-tome-and-principe": "Sao Tome and Principe",
    "africa/senegal-and-gambia": "Senegal and Gambia",
    "africa/seychelles": "Seychelles",
    "africa/sierra-leone": "Sierra Leone",
    "africa/somalia": "Somalia",
    "africa/south-africa": "South Africa",
    "africa/south-africa-and-lesotho": "South Africa (includes Lesotho)",
    "africa/south-sudan": "South Sudan",
    "africa/sudan": "Sudan",
    "africa/swaziland": "Eswatini",
    "africa/tanzania": "Tanzania",
    "africa/togo": "Togo",
    "africa/tunisia": "Tunisia",
    "africa/uganda": "Uganda",
    "africa/zambia": "Zambia",
    "africa/zimbabwe": "Zimbabwe",
    "asia/afghanistan": "Afghanistan",
    "asia/armenia": "Armenia",
    "asia/azerbaijan": "Azerbaijan",
    "asia/bangladesh": "Bangladesh",
    "asia/bhutan": "Bhutan",
    "asia/cambodia": "Cambodia",
    "asia/china": "China",
    "asia/east-timor": "Timor-Leste",
    "asia/gcc-states": "GCC States",
    "asia/india": "India",
    "asia/indonesia": "Indonesia (with East Timor)",
    "asia/iran": "Iran",
    "asia/iraq": "Iraq",
    "asia/israel-and-palestine": "Israel and Palestine",
    "asia/japan": "Japan",
    "asia/jordan": "Jordan",
    "asia/kazakhstan": "Kazakhstan",
    "asia/kyrgyzstan": "Kyrgyzstan",
    "asia/laos": "Laos",
    "asia/lebanon": "Lebanon",
    "asia/malaysia-singapore-brunei": "Malaysia, Singapore, and Brunei",
    "asia/maldives": "Maldives",
    "asia/mongolia": "Mongolia",
    "asia/myanmar": "Myanmar",
    "asia/nepal": "Nepal",
    "asia/north-korea": "North Korea",
    "asia/pakistan": "Pakistan",
    "asia/philippines": "Philippines",
    "asia/south-korea": "South Korea",
    "asia/sri-lanka": "Sri Lanka",
    "asia/syria": "Syria",
    "asia/taiwan": "Taiwan",
    "asia/tajikistan": "Tajikistan",
    "asia/thailand": "Thailand",
    "asia/turkmenistan": "Turkmenistan",
    "asia/uzbekistan": "Uzbekistan",
    "asia/vietnam": "Vietnam",
    "asia/yemen": "Yemen",
    "australia-oceania/american-oceania": "American Oceania",
    "australia-oceania/australia": "Australia",
    "australia-oceania/fiji": "Fiji",
    "australia-oceania/kiribati": "Kiribati",
    "australia-oceania/marshall-islands": "Marshall Islands",
    "australia-oceania/micronesia": "Micronesia",
    "australia-oceania/new-caledonia": "New Caledonia",
    "australia-oceania/new-zealand": "New Zealand",
    "australia-oceania/papua-new-guinea": "Papua New Guinea",
    "australia-oceania/polynesie-francaise": "French Polynesia",
    "australia-oceania/samoa": "Samoa",
    "australia-oceania/solomon-islands": "Solomon Islands",
    "australia-oceania/tonga": "Tonga",
    "australia-oceania/vanuatu": "Vanuatu",
    "central-america/bahamas": "Bahamas",
    "central-america/belize": "Belize",
    "central-america/costa-rica": "Costa Rica",
    "central-america/cuba": "Cuba",
    "central-america/el-salvador": "El Salvador",
    "central-america/guatemala": "Guatemala",
    "central-america/haiti-and-domrep": "Haiti and Dominican Republic",
    "central-america/honduras": "Honduras",
    "central-america/jamaica": "Jamaica",
    "central-america/nicaragua": "Nicaragua",
    "central-america/panama": "Panama",
    "europe/albania": "Albania",
    "europe/alps": "Alps",
    "europe/andorra": "Andorra",
    "europe/austria": "Austria",
    "europe/azores": "Azores",
    "europe/belarus": "Belarus",
    "europe/belgium": "Belgium",
    "europe/bosnia-herzegovina": "Bosnia and Herzegovina",
    "europe/britain-and-ireland": "Britain and Ireland",
    "europe/bulgaria": "Bulgaria",
    "europe/croatia": "Croatia",
    "europe/cyprus": "Cyprus",
    "europe/czech-republic": "Czechia",
    "europe/dach": "Germany, Austria, Switzerland",
    "europe/denmark": "Denmark",
    "europe/estonia": "Estonia",
    "europe/faroe-islands": "Faroe Islands",
    "europe/finland": "Finland",
    "europe/france": "France",
    "europe/georgia": "Georgia",
    "europe/germany": "Germany",
    "europe/greece": "Greece",
    "europe/guernsey-jersey": "Guernsey and Jersey",
    "europe/hungary": "Hungary",
    "europe/iceland": "Iceland",
    "europe/ireland-and-northern-ireland": "Ireland and Northern Ireland",
    "europe/isle-of-man": "Isle of Man",
    "europe/italy": "Italy",
    "europe/kosovo": "Kosovo",
    "europe/latvia": "Latvia",
    "europe/liechtenstein": "Liechtenstein",
    "europe/lithuania": "Lithuania",
    "europe/luxembourg": "Luxembourg",
    "europe/macedonia": "North Macedonia",
    "europe/malta": "Malta",
    "europe/moldova": "Moldova",
    "europe/monaco": "Monaco",
    "europe/montenegro": "Montenegro",
    "europe/netherlands": "Netherlands",
    "europe/norway": "Norway",
    "europe/poland": "Poland",
    "europe/portugal": "Portugal",
    "europe/romania": "Romania",
    "europe/serbia": "Serbia",
    "europe/slovakia": "Slovakia",
    "europe/slovenia": "Slovenia",
    "europe/spain": "Spain",
    "europe/sweden": "Sweden",
    "europe/switzerland": "Switzerland",
    "europe/turkey": "Turkey",
    "europe/ukraine": "Ukraine",
    "europe/united-kingdom": "United Kingdom",
    "north-america/canada": "Canada",
    "north-america/greenland": "Greenland",
    "north-america/mexico": "Mexico",
    "north-america/us-midwest": "US Midwest",
    "north-america/us-northeast": "US Northeast",
    "north-america/us-south": "US South",
    "north-america/us-west": "US West",
    "south-america/argentina": "Argentina",
    "south-america/bolivia": "Bolivia",
    "south-america/brazil": "Brazil",
    "south-america/chile": "Chile",
    "south-america/colombia": "Colombia",
    "south-america/ecuador": "Ecuador",
    "south-america/guyana": "Guyana",
    "south-america/paraguay": "Paraguay",
    "south-america/peru": "Peru",
    "south-america/suriname": "Suriname",
    "south-america/uruguay": "Uruguay",
    "south-america/venezuela": "Venezuela",
    "asia/india/central-zone": "Central Zone",
    "asia/india/eastern-zone": "Eastern Zone",
    "asia/india/north-eastern-zone": "North-Eastern Zone",
    "asia/india/northern-zone": "Northern Zone",
    "asia/india/southern-zone": "Southern Zone",
    "asia/india/western-zone": "Western Zone",
    "asia/indonesia/java": "Java",
    "asia/indonesia/kalimantan": "Kalimantan",
    "asia/indonesia/maluku": "Maluku",
    "asia/indonesia/nusa-tenggara": "Nusa-Tenggara",
    "asia/indonesia/papua": "Papua",
    "asia/indonesia/sulawesi": "Sulawesi",
    "asia/indonesia/sumatra": "Sumatra",
    "asia/japan/chubu": "Chūbu region",
    "asia/japan/chugoku": "Chūgoku region",
    "asia/japan/hokkaido": "Hokkaidō",
    "asia/japan/kansai": "Kansai region (a.k.a. Kinki region)",
    "asia/japan/kanto": "Kantō region",
    "asia/japan/kyushu": "Kyūshū",
    "asia/japan/shikoku": "Shikoku",
    "asia/japan/tohoku": "Tōhoku region",
    "europe/france/alsace": "Alsace",
    "europe/france/aquitaine": "Aquitaine",
    "europe/france/auvergne": "Auvergne",
    "europe/france/basse-normandie": "Basse-Normandie",
    "europe/france/bourgogne": "Bourgogne",
    "europe/france/bretagne": "Bretagne",
    "europe/france/centre": "Centre",
    "europe/france/champagne-ardenne": "Champagne Ardenne",
    "europe/france/corse": "Corse",
    "europe/france/franche-comte": "Franche Comte",
    "europe/france/guadeloupe": "Guadeloupe",
    "europe/france/guyane": "Guyane",
    "europe/france/haute-normandie": "Haute-Normandie",
    "europe/france/ile-de-france": "Ile-de-France",
    "europe/france/languedoc-roussillon": "Languedoc-Roussillon",
    "europe/france/limousin": "Limousin",
    "europe/france/lorraine": "Lorraine",
    "europe/france/martinique": "Martinique",
    "europe/france/mayotte": "Mayotte",
    "europe/france/midi-pyrenees": "Midi-Pyrenees",
    "europe/france/nord-pas-de-calais": "Nord-Pas-de-Calais",
    "europe/france/pays-de-la-loire": "Pays de la Loire",
    "europe/france/picardie": "Picardie",
    "europe/france/poitou-charentes": "Poitou-Charentes",
    "europe/france/provence-alpes-cote-d-azur": "Provence Alpes-Cote-d'Azur",
    "europe/france/reunion": "Reunion",
    "europe/france/rhone-alpes": "Rhone-Alpes",
    "europe/germany/baden-wuerttemberg": "Baden-Württemberg",
    "europe/germany/bayern": "Bayern",
    "europe/germany/berlin": "Berlin",
    "europe/germany/brandenburg": "Brandenburg (mit Berlin)",
    "europe/germany/bremen": "Bremen",
    "europe/germany/hamburg": "Hamburg",
    "europe/germany/hessen": "Hessen",
    "europe/germany/mecklenburg-vorpommern": "Mecklenburg-Vorpommern",
    "europe/germany/niedersachsen": "Niedersachsen (mit Bremen)",
    "europe/germany/nordrhein-westfalen": "Nordrhein-Westfalen",
    "europe/germany/rheinland-pfalz": "Rheinland-Pfalz",
    "europe/germany/saarland": "Saarland",
    "europe/germany/sachsen": "Sachsen",
    "europe/germany/sachsen-anhalt": "Sachsen-Anhalt",
    "europe/germany/schleswig-holstein": "Schleswig-Holstein",
    "europe/germany/thueringen": "Thüringen",
    "europe/italy/centro": "Centro",
    "europe/italy/isole": "Isole",
    "europe/italy/nord-est": "Nord-Est",
    "europe/italy/nord-ovest": "Nord-Ovest",
    "europe/italy/sud": "Sud",
    "europe/netherlands/drenthe": "Drenthe",
    "europe/netherlands/flevoland": "Flevoland",
    "europe/netherlands/friesland": "Friesland",
    "europe/netherlands/gelderland": "Gelderland",
    "europe/netherlands/groningen": "Groningen",
    "europe/netherlands/limburg": "Limburg",
    "europe/netherlands/noord-brabant": "Noord-Brabant",
    "europe/netherlands/noord-holland": "Noord-Holland",
    "europe/netherlands/overijssel": "Overijssel",
    "europe/netherlands/utrecht": "Utrecht",
    "europe/netherlands/zeeland": "Zeeland",
    "europe/netherlands/zuid-holland": "Zuid-Holland",
    "europe/poland/dolnoslaskie": "Województwo dolnośląskie<br />(Lower Silesian Voivodeship)",
    "europe/poland/kujawsko-pomorskie": "Województwo kujawsko-pomorskie<br />(Kuyavian-Pomeranian Voivodeship)",
    "europe/poland/lodzkie": "Województwo łódzkie<br />(Łódź Voivodeship)",
    "europe/poland/lubelskie": "Województwo lubelskie<br />(Lublin Voivodeship)",
    "europe/poland/lubuskie": "Województwo lubuskie<br />(Lubusz Voivodeship)",
    "europe/poland/malopolskie": "Województwo małopolskie<br />(Lesser Poland Voivodeship)",
    "europe/poland/mazowieckie": "Województwo mazowieckie<br />(Mazovian Voivodeship)",
    "europe/poland/opolskie": "Województwo opolskie<br />(Opole Voivodeship)",
    "europe/poland/podkarpackie": "Województwo podkarpackie<br />(Subcarpathian Voivodeship)",
    "europe/poland/podlaskie": "Województwo podlaskie<br />(Podlaskie Voivodeship)",
    "europe/poland/pomorskie": "Województwo pomorskie<br />(Pomeranian Voivodeship)",
    "europe/poland/slaskie": "Województwo śląskie<br />(Silesian Voivodeship)",
    "europe/poland/swietokrzyskie": "Województwo świętokrzyskie<br />(Świętokrzyskie Voivodeship)",
    "europe/poland/warminsko-mazurskie": "Województwo warmińsko-mazurskie<br />(Warmian-Masurian Voivodeship)",
    "europe/poland/wielkopolskie": "Województwo wielkopolskie<br />(Greater Poland Voivodeship)",
    "europe/poland/zachodniopomorskie": "Województwo zachodniopomorskie<br />(West Pomeranian Voivodeship)",
    "europe/spain/andalucia": "Andalucía",
    "europe/spain/aragon": "Aragón",
    "europe/spain/asturias": "Asturias",
    "europe/spain/cantabria": "Cantabria",
    "europe/spain/castilla-la-mancha": "Castilla-La Mancha",
    "europe/spain/castilla-y-leon": "Castilla y León",
    "europe/spain/cataluna": "Cataluña",
    "europe/spain/ceuta": "Ceuta",
    "europe/spain/extremadura": "Extremadura",
    "europe/spain/galicia": "Galicia",
    "europe/spain/islas-baleares": "Islas Baleares",
    "europe/spain/la-rioja": "La Rioja",
    "europe/spain/madrid": "Madrid",
    "europe/spain/melilla": "Melilla",
    "europe/spain/murcia": "Murcia",
    "europe/spain/navarra": "Navarra",
    "europe/spain/pais-vasco": "País Vasco",
    "europe/spain/valencia": "Valencia",
    "europe/united-kingdom/england": "England",
    "europe/united-kingdom/scotland": "Scotland",
    "europe/united-kingdom/wales": "Wales",
    "north-america/canada/alberta": "Alberta",
    "north-america/canada/british-columbia": "British Columbia",
    "north-america/canada/manitoba": "Manitoba",
    "north-america/canada/new-brunswick": "New Brunswick",
    "north-america/canada/newfoundland-and-labrador": "Newfoundland and Labrador",
    "north-america/canada/northwest-territories": "Northwest Territories",
    "north-america/canada/nova-scotia": "Nova Scotia",
    "north-america/canada/nunavut": "Nunavut",
    "north-america/canada/ontario": "Ontario",
    "north-america/canada/prince-edward-island": "Prince Edward Island",
    "north-america/canada/quebec": "Quebec",
    "north-america/canada/saskatchewan": "Saskatchewan",
    "north-america/canada/yukon": "Yukon",
    "north-america/us/alabama": "us/alabama",
    "north-america/us/alaska": "us/alaska",
    "north-america/us/arizona": "us/arizona",
    "north-america/us/arkansas": "us/arkansas",
    "north-america/us/california": "us/california",
    "north-america/us/colorado": "us/colorado",
    "north-america/us/connecticut": "us/connecticut",
    "north-america/us/delaware": "us/delaware",
    "north-america/us/district-of-columbia": "us/district-of-columbia",
    "north-america/us/florida": "us/florida",
    "north-america/us/hawaii": "us/hawaii",
    "north-america/us/idaho": "us/idaho",
    "north-america/us/illinois": "us/illinois",
    "north-america/us/indiana": "us/indiana",
    "north-america/us/iowa": "us/iowa",
    "north-america/us/kansas": "us/kansas",
    "north-america/us/kentucky": "us/kentucky",
    "north-america/us/louisiana": "us/louisiana",
    "north-america/us/maine": "us/maine",
    "north-america/us/maryland": "us/maryland",
    "north-america/us/massachusetts": "us/massachusetts",
    "north-america/us/michigan": "us/michigan",
    "north-america/us/minnesota": "us/minnesota",
    "north-america/us/mississippi": "us/mississippi",
    "north-america/us/missouri": "us/missouri",
    "north-america/us/montana": "us/montana",
    "north-america/us/nebraska": "us/nebraska",
    "north-america/us/nevada": "us/nevada",
    "north-america/us/new-hampshire": "us/new-hampshire",
    "north-america/us/new-jersey": "us/new-jersey",
    "north-america/us/new-mexico": "us/new-mexico",
    "north-america/us/new-york": "us/new-york",
    "north-america/us/north-carolina": "us/north-carolina",
    "north-america/us/north-dakota": "us/north-dakota",
    "north-america/us/ohio": "us/ohio",
    "north-america/us/oklahoma": "us/oklahoma",
    "north-america/us/oregon": "us/oregon",
    "north-america/us/pennsylvania": "us/pennsylvania",
    "north-america/us/puerto-rico": "us/puerto-rico",
    "north-america/us/rhode-island": "us/rhode-island",
    "north-america/us/south-carolina": "us/south-carolina",
    "north-america/us/south-dakota": "us/south-dakota",
    "north-america/us/tennessee": "us/tennessee",
    "north-america/us/texas": "us/texas",
    "north-america/us/us-virgin-islands": "us/us-virgin-islands",
    "north-america/us/utah": "us/utah",
    "north-america/us/vermont": "us/vermont",
    "north-america/us/virginia": "us/virginia",
    "north-america/us/washington": "us/washington",
    "north-america/us/west-virginia": "us/west-virginia",
    "north-america/us/wisconsin": "us/wisconsin",
    "north-america/us/wyoming": "us/wyoming",
    "south-america/brazil/centro-oeste": "Centro-Oeste",
    "south-america/brazil/nordeste": "Nordeste",
    "south-america/brazil/norte": "Norte",
    "south-america/brazil/sudeste": "Sudeste",
    "south-america/brazil/sul": "Sul",
    "north-america/us/california/norcal": "Northern California",
    "north-america/us/california/socal": "Southern California"
}


# Provider titles are source metadata, not display-ready markup. Some US
# titles contain their source path instead of a geographic name.
for _path, _name in tuple(REGION_NAMES.items()):
    _name = unescape(re.sub(r"<[^>]*>", " ", _name))
    _name = " ".join(_name.split())
    if _name.startswith("us/"):
        _name = _path.rsplit("/", 1)[-1].replace("-", " ").title()
    REGION_NAMES[_path] = _name
REGION_NAMES.update({
    "north-america/us": "United States",
    "north-america/us/district-of-columbia": "District of Columbia",
    "north-america/us/us-virgin-islands": "US Virgin Islands",
    "europe/germany/bayern": "Bavaria",
})
COUNTRY_CODES["us"] = ("US",)


def geography(path):
    parts = path.split('/')
    name = REGION_NAMES.get(path, parts[-1].replace('-', ' ').title())
    codes = COUNTRY_CODES.get(parts[1], ()) if len(parts) > 1 else ()
    # The whole Indonesia extract includes Timor-Leste, but that does not
    # establish Timor-Leste coverage for every individual Indonesian island.
    if len(parts) > 2 and parts[1] == "indonesia":
        codes = ("ID",)
    kind = 'multiCountry' if len(codes) > 1 else 'country'
    if len(parts) > 2 or parts[-1] in {
        'canary-islands', 'azores', 'us-midwest', 'us-northeast', 'us-south', 'us-west'
    }:
        kind = 'subregion'
    if not codes:
        kind = 'subregion'  # Unknown country coverage, valid native region category.
    identity = re.sub('[^A-Z0-9]', '', parts[-1].upper())
    aliases = {'CZECHREPUBLIC': 'CZECHIA', 'MACEDONIA': 'NORTHMACEDONIA',
               'SWAZILAND': 'ESWATINI'}
    identity = aliases.get(identity, identity)
    # Countries keep existing canonical keys for cross-provider statistics;
    # subdivisions use source-parent context to prevent Georgia/US Georgia
    # and future same-named subdivisions from collapsing.
    if len(parts) > 2:
        identity = '-'.join(parts[1:]).upper()
        parent = ("Indonesia" if parts[1] == "indonesia" else
                  REGION_NAMES.get('/'.join(parts[:2]), parts[1].replace('-', ' ').title()))
        name = f"{name} – {parent}"
    return name, identity, codes, kind
