"""Reviewed geographic identity; never a package membership allowlist.

Mapped from upstream country.txt Geofabrik extract paths, inspected 2026-09-10:
https://gitlab.com/ravenfeld/garmincustommap/-/raw/master/country.txt
Known combined extract names are explicit below. Unmapped new packages retain
unknown geography and remain discoverable. No source map data is bundled.
"""

REGION_GEOGRAPHY = {
    "polynesie-francaise": (("PF",), "subregion"),
    "irlande": (("IE", "GB"), "multiCountry"),
    'acores': (('PT',), 'subregion'),
    'afrique-du-sud': (('ZA',), 'country'),
    'albanie': (('AL',), 'country'),
    'alberta': (('CA',), 'subregion'),
    'algerie': (('DZ',), 'country'),
    'allemagne': (('DE',), 'country'),
    'alpes': (('AT', 'CH', 'DE', 'FR', 'IT', 'LI', 'SI'), 'multiCountry'),
    'andorre': (('AD',), 'country'),
    'argentine': (('AR',), 'country'),
    'arizona': (('US',), 'subregion'),
    'australie': (('AU',), 'country'),
    'autriche': (('AT',), 'country'),
    'belgique': (('BE',), 'country'),
    'benin': (('BJ',), 'country'),
    'bolivie': (('BO',), 'country'),
    'bouthan': (('BT',), 'country'),
    'bresil-sud': (('BR',), 'subregion'),
    'bresil-sud-est': (('BR',), 'subregion'),
    'bulgarie': (('BG',), 'country'),
    'burkina-faso': (('BF',), 'country'),
    'californie': (('US',), 'subregion'),
    'cambodge': (('KH',), 'country'),
    'cap-vert': (('CV',), 'country'),
    'chili': (('CL',), 'country'),
    'colombie': (('CO',), 'country'),
    'colombie-britannique': (('CA',), 'subregion'),
    'colorado': (('US',), 'subregion'),
    'coree-du-sud': (('KR',), 'country'),
    'costa-rica': (('CR',), 'country'),
    'cote-ivoire': (('CI',), 'country'),
    'croatie': (('HR',), 'country'),
    'cuba': (('CU',), 'country'),
    'danemark': (('DK',), 'country'),
    'djibouti': (('DJ',), 'country'),
    'dominique': (('DM',), 'country'),
    'ecosse': (('GB',), 'subregion'),
    'egypte': (('EG',), 'country'),
    'espagne': (('ES',), 'country'),
    'finlande': (('FI',), 'country'),
    'france': (('FR',), 'country'),
    'france-courbes-ign': (('FR',), 'country'),
    'gcc-states': (('AE', 'BH', 'KW', 'OM', 'QA', 'SA'), 'multiCountry'),
    'georgie': (('GE',), 'country'),
    'grande-bretagne': (('GB',), 'country'),
    'grece': (('GR',), 'country'),
    'guadeloupe': (('FR',), 'subregion'),
    'guatemala': (('GT',), 'country'),
    'guyane': (('FR',), 'subregion'),
    'haiti-et-republique-dominicaine': (('HT', 'DO'), 'multiCountry'),
    'hawaii': (('US',), 'subregion'),
    'hongrie': (('HU',), 'country'),
    'iles-canaries': (('ES',), 'subregion'),
    'iles-feroe': (('FO',), 'country'),
    'inde-du-sud': (('IN',), 'subregion'),
    'indonesie': (('ID',), 'country'),
    'islande': (('IS',), 'country'),
    'israel-palestine': (('IL', 'PS'), 'multiCountry'),
    'italie': (('IT',), 'country'),
    'japon': (('JP',), 'country'),
    'jordanie': (('JO',), 'country'),
    'kenya': (('KE',), 'country'),
    'liban': (('LB',), 'country'),
    'libye': (('LY',), 'country'),
    'lituanie': (('LT',), 'country'),
    'luxembourg': (('LU',), 'country'),
    'macedoine': (('MK',), 'country'),
    'madagascar': (('MG',), 'country'),
    'maine': (('US',), 'subregion'),
    'malaisie-singapour-brunei': (('MY', 'SG', 'BN'), 'multiCountry'),
    'mali': (('ML',), 'country'),
    'malte': (('MT',), 'country'),
    'maroc': (('MA',), 'country'),
    'martinique': (('FR',), 'subregion'),
    'massachusetts': (('US',), 'subregion'),
    'maurice': (('MU',), 'country'),
    'mauritanie': (('MR',), 'country'),
    'mayotte': (('FR',), 'subregion'),
    'mexique': (('MX',), 'country'),
    'michigan': (('US',), 'subregion'),
    'montenegro': (('ME',), 'country'),
    'mozambique': (('MZ',), 'country'),
    'namibie': (('NA',), 'country'),
    'nepal': (('NP',), 'country'),
    'nevada': (('US',), 'subregion'),
    'new-hampshire': (('US',), 'subregion'),
    'new-york': (('US',), 'subregion'),
    'niger': (('NE',), 'country'),
    'norvege': (('NO',), 'country'),
    'nouveau-brunswick': (('CA',), 'subregion'),
    'nouveau-mexique': (('US',), 'subregion'),
    'nouvelle-caledonie': (('NC',), 'country'),
    'nouvelle-zelande': (('NZ',), 'country'),
    'ontario': (('CA',), 'subregion'),
    'oregon': (('US',), 'subregion'),
    'ouganda': (('UG',), 'country'),
    'pays-bas': (('NL',), 'country'),
    'perou': (('PE',), 'country'),
    'philippines': (('PH',), 'country'),
    'pologne': (('PL',), 'country'),
    'portugal': (('PT',), 'country'),
    'quebec': (('CA',), 'subregion'),
    'republique-tcheque': (('CZ',), 'country'),
    'reunion': (('FR',), 'subregion'),
    'roumanie': (('RO',), 'country'),
    'saint-barthelemy': (('BL',), 'country'),
    'saint-martin': (('MF',), 'country'),
    'senegal-et-gambie': (('SN', 'GM'), 'multiCountry'),
    'seychelles': (('SC',), 'country'),
    'slovaquie': (('SK',), 'country'),
    'slovenie': (('SI',), 'country'),
    'sri-lanka': (('LK',), 'country'),
    'suede': (('SE',), 'country'),
    'suisse': (('CH',), 'country'),
    'taiwan': (('TW',), 'country'),
    'tanzanie': (('TZ',), 'country'),
    'texas': (('US',), 'subregion'),
    'thailand': (('TH',), 'country'),
    'tunisie': (('TN',), 'country'),
    'turquie': (('TR',), 'country'),
    'ukraine': (('UA',), 'country'),
    'utah': (('US',), 'subregion'),
    'vanuatu': (('VU',), 'country'),
    'vermont': (('US',), 'subregion'),
    'vietnam': (('VN',), 'country'),
    'washington': (('US',), 'subregion'),
    'wyoming': (('US',), 'subregion'),
    'zimbabwe': (('ZW',), 'country'),
}

# Additional unambiguous country/subregion names in the official directory
# index on 2026-09-10, not yet listed in upstream country.txt.
REGION_GEOGRAPHY.update({
    'bresil-nord': (('BR',), 'subregion'),
    'bresil-nord-est': (('BR',), 'subregion'),
    'caroline-du-nord': (('US',), 'subregion'),
    'caroline-du-sud': (('US',), 'subregion'),
    'comores': (('KM',), 'country'),
    'equateur': (('EC',), 'country'),
    'estonie': (('EE',), 'country'),
    'floride': (('US',), 'subregion'),
    'france-taaf': (('TF',), 'subregion'),
    'guangdong': (('CN',), 'subregion'),
    'hebei': (('CN',), 'subregion'),
    'idaho': (('US',), 'subregion'),
    'illinois': (('US',), 'subregion'),
    'indiana': (('US',), 'subregion'),
    'jamaique': (('JM',), 'country'),
    'jiangsu': (('CN',), 'subregion'),
    'kirghizistan': (('KG',), 'country'),
    'laos': (('LA',), 'country'),
    'lettonie': (('LV',), 'country'),
    'manitoba': (('CA',), 'subregion'),
    'montana': (('US',), 'subregion'),
    'ohio': (('US',), 'subregion'),
    'pakistan': (('PK',), 'country'),
    'pennsylvanie': (('US',), 'subregion'),
    'republique-centre-afrique': (('CF',), 'country'),
    'serbie': (('RS',), 'country'),
    'shanghai': (('CN',), 'subregion'),
    'tchad': (('TD',), 'country'),
    'terre-neuve-et-labrador': (('CA',), 'subregion'),
    'wisconsin': (('US',), 'subregion'),
    'zhejiang': (('CN',), 'subregion'),
})


# English presentation labels only. Never used for package identity, policy,
# ownership, or catalog membership. Unknown future regions keep upstream wording.
REGION_DISPLAY_NAMES = {
    'acores': 'Azores',
    'afrique-du-sud': 'South Africa',
    'albanie': 'Albania',
    'alberta': 'Alberta',
    'algerie': 'Algeria',
    'allemagne': 'Germany',
    'alpes': 'Alps',
    'andorre': 'Andorra',
    'argentine': 'Argentina',
    'arizona': 'Arizona',
    'australie': 'Australia',
    'autriche': 'Austria',
    'belgique': 'Belgium',
    'benin': 'Benin',
    'bolivie': 'Bolivia',
    'bouthan': 'Bhutan',
    'bresil-nord': 'Brazil North',
    'bresil-nord-est': 'Brazil Northeast',
    'bresil-sud': 'Brazil South',
    'bresil-sud-est': 'Brazil Southeast',
    'bulgarie': 'Bulgaria',
    'burkina-faso': 'Burkina Faso',
    'californie': 'California',
    'cambodge': 'Cambodia',
    'cap-vert': 'Cape Verde',
    'caroline-du-nord': 'North Carolina',
    'caroline-du-sud': 'South Carolina',
    'chili': 'Chile',
    'colombie': 'Colombia',
    'colombie-britannique': 'British Columbia',
    'colorado': 'Colorado',
    'comores': 'Comoros',
    'coree-du-sud': 'South Korea',
    'costa-rica': 'Costa Rica',
    'cote-ivoire': 'Côte d’Ivoire',
    'croatie': 'Croatia',
    'cuba': 'Cuba',
    'danemark': 'Denmark',
    'djibouti': 'Djibouti',
    'dominique': 'Dominica',
    'ecosse': 'Scotland',
    'egypte': 'Egypt',
    'equateur': 'Ecuador',
    'espagne': 'Spain',
    'estonie': 'Estonia',
    'finlande': 'Finland',
    'floride': 'Florida',
    'france': 'France',
    'france-courbes-ign': 'France (IGN contours)',
    'france-taaf': 'French Southern and Antarctic Lands',
    'gcc-states': 'GCC States',
    'georgie': 'Georgia',
    'grande-bretagne': 'Great Britain',
    'grece': 'Greece',
    'guadeloupe': 'Guadeloupe',
    'guangdong': 'Guangdong',
    'guatemala': 'Guatemala',
    'guyane': 'French Guiana',
    'haiti-et-republique-dominicaine': 'Haiti and Dominican Republic',
    'hawaii': 'Hawaii',
    'hebei': 'Hebei',
    'hongrie': 'Hungary',
    'idaho': 'Idaho',
    'iles-canaries': 'Canary Islands',
    'iles-feroe': 'Faroe Islands',
    'illinois': 'Illinois',
    'inde-du-sud': 'India South',
    'indiana': 'Indiana',
    'indonesie': 'Indonesia',
    'irlande': 'Ireland and Northern Ireland',
    'islande': 'Iceland',
    'israel-palestine': 'Israel and Palestine',
    'italie': 'Italy',
    'jamaique': 'Jamaica',
    'japon': 'Japan',
    'jiangsu': 'Jiangsu',
    'jordanie': 'Jordan',
    'kenya': 'Kenya',
    'kirghizistan': 'Kyrgyzstan',
    'laos': 'Laos',
    'lettonie': 'Latvia',
    'liban': 'Lebanon',
    'libye': 'Libya',
    'lituanie': 'Lithuania',
    'luxembourg': 'Luxembourg',
    'macedoine': 'North Macedonia',
    'madagascar': 'Madagascar',
    'maine': 'Maine',
    'malaisie-singapour-brunei': 'Malaysia, Singapore and Brunei',
    'mali': 'Mali',
    'malte': 'Malta',
    'manitoba': 'Manitoba',
    'maroc': 'Morocco',
    'martinique': 'Martinique',
    'massachusetts': 'Massachusetts',
    'maurice': 'Mauritius',
    'mauritanie': 'Mauritania',
    'mayotte': 'Mayotte',
    'mexique': 'Mexico',
    'michigan': 'Michigan',
    'montana': 'Montana',
    'montenegro': 'Montenegro',
    'mozambique': 'Mozambique',
    'namibie': 'Namibia',
    'nepal': 'Nepal',
    'nevada': 'Nevada',
    'new-hampshire': 'New Hampshire',
    'new-york': 'New York',
    'niger': 'Niger',
    'norvege': 'Norway',
    'nouveau-brunswick': 'New Brunswick',
    'nouveau-mexique': 'New Mexico',
    'nouvelle-caledonie': 'New Caledonia',
    'nouvelle-zelande': 'New Zealand',
    'ohio': 'Ohio',
    'ontario': 'Ontario',
    'oregon': 'Oregon',
    'ouganda': 'Uganda',
    'pakistan': 'Pakistan',
    'pays-bas': 'Netherlands',
    'pennsylvanie': 'Pennsylvania',
    'perou': 'Peru',
    'philippines': 'Philippines',
    'pologne': 'Poland',
    'polynesie-francaise': 'French Polynesia',
    'portugal': 'Portugal',
    'quebec': 'Quebec',
    'republique-centre-afrique': 'Central African Republic',
    'republique-tcheque': 'Czechia',
    'reunion': 'Réunion',
    'roumanie': 'Romania',
    'saint-barthelemy': 'St. Barthélemy',
    'saint-martin': 'St. Martin',
    'senegal-et-gambie': 'Senegal and Gambia',
    'serbie': 'Serbia',
    'seychelles': 'Seychelles',
    'shanghai': 'Shanghai',
    'slovaquie': 'Slovakia',
    'slovenie': 'Slovenia',
    'sri-lanka': 'Sri Lanka',
    'suede': 'Sweden',
    'suisse': 'Switzerland',
    'taiwan': 'Taiwan',
    'tanzanie': 'Tanzania',
    'tchad': 'Chad',
    'terre-neuve-et-labrador': 'Newfoundland and Labrador',
    'texas': 'Texas',
    'thailand': 'Thailand',
    'tunisie': 'Tunisia',
    'turquie': 'Türkiye',
    'ukraine': 'Ukraine',
    'utah': 'Utah',
    'vanuatu': 'Vanuatu',
    'vermont': 'Vermont',
    'vietnam': 'Vietnam',
    'washington': 'Washington',
    'wisconsin': 'Wisconsin',
    'wyoming': 'Wyoming',
    'zhejiang': 'Zhejiang',
    'zimbabwe': 'Zimbabwe',
}


def maprando_display_name(slug: str, original_region: str) -> str:
    return REGION_DISPLAY_NAMES.get(slug, original_region.replace("_", " ").strip())
