const {PGlite}=require(process.argv[2]);
const fs=require('fs'),assert=require('node:assert/strict'); const q=JSON.parse(fs.readFileSync(0,'utf8'));
(async()=>{
const db=new PGlite();await db.exec(q.schema);
await db.exec(`ALTER TABLE compatibility_evidence_event ADD COLUMN statistics_exclusion_code text;
ALTER TABLE map_download_event ADD COLUMN map_result_index int,ADD COLUMN is_local_test boolean DEFAULT false,ADD COLUMN statistics_exclusion_code text,ADD COLUMN component_kind text,ADD COLUMN acquisition_id uuid,ADD COLUMN acquisition_purpose text,ADD COLUMN app_build text;
CREATE TABLE map_provider(id text,name text);
CREATE TABLE map_package(id text,provider_id text,name text,map_type text,region text,provider_region_id text,canonical_region_id text,geographic_region_id text,country text);
CREATE TABLE map_update_diagnostic(event_id uuid,operation_id uuid,provider text,region text,outcome text,canonical_device_model_id text,is_local_test boolean,payload jsonb);
INSERT INTO map_provider VALUES('maprando','MapRando');
INSERT INTO map_package VALUES('map-a','maprando','Map A','main','FRANCE','france','FRANCE','FR','FR'),('map-b','maprando','Map B','main','FRANCE','france','FRANCE','FR','FR'),('maprando-france-courbes-ign','maprando','Contours','main','FRANCECOURBESIGN','france-courbes-ign','FRANCECOURBESIGN','FR','FR');
INSERT INTO device_model VALUES('model-a',true),('model-b',true);`);
await db.exec(q.previousView);
const previousColumns=(await db.query("SELECT column_name,data_type FROM information_schema.columns WHERE table_name='compatibility_model_statistics' ORDER BY ordinal_position")).rows;
await db.exec(q.view);
assert.deepEqual((await db.query("SELECT column_name,data_type FROM information_schema.columns WHERE table_name='compatibility_model_statistics' ORDER BY ordinal_position")).rows,previousColumns);
let num=100;const uuid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;const op=uuid(1),acq=uuid(2);
const run=async(n)=> (await db.query(q[n].sql,q[n].params)).rows;
const reset=()=>db.exec('TRUNCATE compatibility_evidence_event,map_download_event,map_update_diagnostic');
async function diag(o={}){const x={idx:0,region:'FRANCE',outcome:'SUCCEEDED',finish:'VERIFIED',write:true,model:'model-a',at:'2026-10-05T10:30:00Z',excluded:null,...o};await db.query(`INSERT INTO compatibility_evidence_event(event_id,operation_id,map_result_index,model,compatibility_identity,canonical_device_model_id,identity_assessment,provider,region,phase_outcome,automatic_finishing_result,write_started,app_build,release_label,occurred_at,statistics_exclusion_code) VALUES($1,$2,$3,$4,$4,$4,'{}','maprando',$5,$6,$7,$8,'40','beta18',$9,$10)`,[uuid(num++),op,x.idx,x.model,x.region,x.outcome,x.finish,x.write,x.at,x.excluded]);}
async function event(o={}){const x={idx:0,map:'map-a',region:'FRANCE',type:'INSTALL_SUCCEEDED',outcome:'SUCCEEDED',at:'2026-10-05T10:30:01Z',component:null,acquisition:null,excluded:null,...o};await db.query(`INSERT INTO map_download_event(event_id,operation_id,map_result_index,provider_id,map_package_id,region,event_type,outcome,occurred_at,component_kind,acquisition_id,statistics_exclusion_code) VALUES($1,$2,$3,'maprando',$4,$5,$6,$7,$8,$9,$10,$11)`,[uuid(num++),op,x.idx,x.map,x.region,x.type,x.outcome,x.at,x.component,x.acquisition,x.excluded]);}
const totals=rows=>Object.fromEntries([...new Set(rows.map(r=>r.event_type))].map(t=>[t,rows.filter(r=>r.event_type===t).reduce((s,r)=>s+Number(r.operation_count),0)]));
const count=(rows,type)=>totals(rows)[type]||0;
const success=async()=>count(await run('stats'),'INSTALL_SUCCEEDED');
const model=async()=> (await db.query('SELECT COALESCE(sum(successful_install_count),0)::int AS n FROM compatibility_model_statistics')).rows[0].n;
await diag();await event();assert.equal(await success(),1);
await diag({idx:1});assert.equal((await run('link'))[0].fresh_map_attempt_count,1);
await reset();await event({idx:0});await event({idx:1});await diag();let link=(await run('link'))[0];assert.equal(link.fresh_map_attempt_count,2);assert.equal(link.fresh_map_missing_diagnostic_count,1);assert.equal(Number(link.fresh_map_coverage_rate),50);
await reset();await event();await diag({excluded:'OUT_OF_SCOPE_PREWRITE',outcome:'NOT_STARTED',finish:'NOT_REACHED',write:false});assert.equal((await run('link'))[0].fresh_map_linked_diagnostic_count,0);
await reset();await diag();assert.equal(count(await run('period'),'INSTALL_SUCCEEDED'),1);await event({at:'2026-10-05T11:00:01Z'});assert.equal(count(await run('period'),'INSTALL_SUCCEEDED'),1);
await reset();await diag();await diag({outcome:'FAILED',finish:'FAILED'});await event();assert.equal(await success(),0);
await reset();await diag({model:'model-a'});await diag({model:'model-b',outcome:'FAILED',finish:'FAILED'});assert.equal(await model(),0);
await reset();await diag({idx:0});await diag({idx:1,outcome:'FAILED',finish:'FAILED'});assert.equal(await model(),1);await db.exec("UPDATE compatibility_evidence_event SET diagnostic_status='RESOLVED'");assert.equal(await model(),1);await db.exec("UPDATE compatibility_evidence_event SET diagnostic_status='ACTIVE'");assert.equal(await model(),1);
await reset();await diag({region:'FRANCECOURBESIGN'});assert.equal(await model(),1);assert.equal(await success(),1);
await reset();await event({type:'DOWNLOAD_SUCCEEDED',acquisition:acq,component:'main'});await event({type:'DOWNLOAD_FAILED',outcome:'FAILED',acquisition:acq,component:'main'});assert.equal(count(await run('stats'),'DOWNLOAD_SUCCEEDED'),0);assert.equal(count(await run('stats'),'DOWNLOAD_FAILED'),0);
await reset();await event({type:'DOWNLOAD_SUCCEEDED',acquisition:acq,component:'main'});await event({type:'DOWNLOAD_SUCCEEDED',acquisition:acq,component:'main',at:'2026-10-05T11:30:00Z'});assert.equal(count(await run('stats'),'DOWNLOAD_SUCCEEDED'),1);assert.equal((await run('trend')).reduce((s,r)=>s+Number(r.download_success_count),0),1);
await reset();await diag();await event({component:'contours'});assert.equal(await success(),1);
await reset();await diag();await event({excluded:'OUT_OF_SCOPE_PREWRITE'});assert.equal(await success(),1);
await reset();await diag();await event({outcome:'FAILED'});assert.equal(await success(),1);
await reset();await diag({outcome:'FAILED',finish:'FAILED'});await event();assert.equal(await success(),0);assert.equal(count(await run('stats'),'INSTALL_FAILED'),0);
await reset();await event();await event({at:'2026-10-05T11:30:00Z'});assert.equal(await success(),1);assert.equal((await run('trend')).reduce((s,r)=>s+Number(r.success_count),0),1);
await reset();await event({type:'DOWNLOAD_SUCCEEDED',acquisition:acq,component:'main',at:'2026-10-25T00:30:00Z'});await event({type:'DOWNLOAD_SUCCEEDED',acquisition:uuid(3),component:'main',at:'2026-10-25T01:30:00Z'});let dst=await run('dst');assert.equal(dst.length,2);assert.equal(dst.reduce((s,r)=>s+Number(r.download_success_count),0),2);
await reset();await diag({outcome:'FAILED',finish:'FAILED',write:false});await event({type:'INSTALL_FAILED',outcome:'FAILED'});assert.equal(count(await run('stats'),'INSTALL_FAILED'),0);assert.equal((await run('link'))[0].fresh_map_attempt_count,0);
await reset();await diag({outcome:'FAILED',finish:'FAILED',write:true});await event({type:'INSTALL_FAILED',outcome:'FAILED'});assert.equal(count(await run('stats'),'INSTALL_FAILED'),1);assert.equal((await run('link'))[0].fresh_map_attempt_count,1);
await reset();await diag();await event({at:'2026-10-05T11:00:01Z'});assert.equal((await run('link_period'))[0].fresh_map_attempt_count,1);
await reset();await diag({idx:0});await diag({idx:1});await event({idx:null});assert.equal(await success(),2);
await reset();await event({map:'map-a'});await event({map:'map-b'});assert.equal(await success(),0);assert.equal((await run('link'))[0].fresh_map_attempt_count,0);
await reset();await diag();await event({component:'contours'});assert.equal((await run('link'))[0].fresh_map_attempt_count,0);
await reset();await event({idx:0});await event({idx:1});assert.equal((await run('activity')).filter(r=>r.event_type==='INSTALL_SUCCEEDED').length,2);
await reset();await event({type:'DOWNLOAD_SUCCEEDED',idx:null});await event({idx:0});assert.equal((await run('activity')).filter(r=>r.event_type==='INSTALL_SUCCEEDED').length,1);
await reset();await diag({at:'2026-10-05T09:00:00Z',outcome:'FAILED',finish:'FAILED'});await diag({at:'2026-10-05T10:30:00Z'});assert.equal((await run('activity')).filter(r=>r.event_type==='INSTALL_SUCCEEDED').length,0);
await db.close();console.log('statistics integrity PASS');
})().catch(e=>{console.error(e);process.exit(1)});
